Controlador vehiculo
ferromarket/backend pull request #47
Opened 2022-08-20 21:05 UTC by Cristianlr95

2022-08-20 23:11 UTC, cromerc requested changes

2022-08-20 23:11 UTC, cromerc commented on models/vehiculo.go
>  	RepartidorID uint64 `json:"RepartidorID"`
Falta los etiquetas de gorm.

2022-08-22 01:59 UTC, Cristianlr95 commented on models/vehiculo.go
>  	RepartidorID uint64 `json:"RepartidorID"`
Corregido (Y)

2022-08-22 02:00 UTC, cromerc approved these changes

2022-08-22 02:00 UTC, merged